# Paths to dependencies
foldseek_path: "foldseek"   

# Execution Configurations
foldseek_threads: 8
esm3di_threads: 4
esm3di_gpus: null                

# MAD Rooting Configurations
mad_path: "madroot/mad"

# ProsTt5 Configurations
use_prostt5: false
prostt5_model_path: "prostt5/prostt5_model.pt"
